### ISSUE TITLE
Get Player/s Rest GET endpoint

### ISSUE THREAD

**Issue by Balugrizzly** [BloomGameStudio/PlayerService#17]
Implement a `GET`Rest Endpoint for the player object/s that output Player data.

**Comment by Sarahtonein** [comment]
Hi Balu,

I have made a start in this initial commit, works locally:

https://github.com/BloomGameStudio/PlayerService/commit/37f799af939287b95cf8c26abf34a2ca7be02df6

**Comment by Sarahtonein** [comment]
Updated endpoint as per discussion with Balu https://github.com/BloomGameStudio/PlayerService/commit/649259c63706b5e9deaa82b3f4894064829929af

**Comment by Sarahtonein** [comment]
Was there anything further we need to review together on this issue @Balugrizzly ? Basic functionality has been created.

**Comment by Balugrizzly** [comment]
No All Good
