### ISSUE TITLE
Sus Memory & Goroutines

### ISSUE THREAD

**Issue by Balugrizzly** [BloomGameStudio/PlayerService#25]
I suspect a memory leak and or leaky go routines in the Player web socket controller

The memory usage is suspiciously increasing over time it seems to be correlated to opened sockets.
The emphasis is on "opened" and not open ones 

The number of Go routines measured by "runtime.NumGoroutine()" is definitely increasing for the number of connections opened and not decreasing after they are closed.

Manually calling "runtime.Goexit()" keeps the number of Go routines down and yields the expected behavior in that regard.

Goals:
- Determine if there is leak or if this is normal behavior 
- Fix the leak if there is one

**Comment by Sarahtonein** [comment]
Mentioned in discord but I will add here. 

I am not sure on the right path but I first:

1. Tried to replicate the behavior

func Count(c echo.Context) error {
    goroutineCount := runtime.NumGoroutine()
    return c.JSON(http.StatusOK, map[string]interface{}{
        "goroutine_count": goroutineCount,
    })
}

I could now send POST requests to get the count of goRoutines.

I then used pprof to look at the goroutine to look at the routine profiles. After terminating a websocket connection this was observed in goroutine information:

1 @ 0x7ff6321a0ece 0x7ff632169de5 0x7ff632169a37 0x7ff63269f5b1 0x7ff6321d25a1
#    0x7ff63269f5b0    github.com/BloomGameStudio/PlayerService/controllers.playerWriter+0x4b0    C:/users/dev/Bloom/PlayerService/controllers/ws_player.go:89

Does this indicate that something related to playerWriter is not exiting properly when the websocket connection is terminated?

**Comment by Sarahtonein** [comment]
Realized I said POST, I meant GET requests.

**Comment by Sarahtonein** [comment]
Tried using a different websocket import and did not observe any different behavior.

**Comment by Sarahtonein** [comment]
Balu, are you content to close this issue now?

**Comment by Balugrizzly** [comment]
Yea Sure
