### ISSUE TITLE
Add automatic Docker Builds For <dev> and <staging> branch

### ISSUE THREAD

**Issue by Balugrizzly** [BloomGameStudio/PlayerService#52]

**Comment by Sarahtonein** [comment]
@Balugrizzly , is there an existing docker account / token that can be used for this?

**Comment by Balugrizzly** [comment]
You can use the github container registry as i have already done with the container from main via docker-publish.yml in .github dir

**Comment by Sarahtonein** [comment]
@Balugrizzly , I've worked off the existing code / action for this change.
