### ISSUE TITLE
Crud Rest For Player

### ISSUE THREAD

**Issue by Balugrizzly** [BloomGameStudio/PlayerService#59]
- Create Full Rest Crud Ressources for the player ( main priority should have the delete)

*Could be Split into further issues if desired

**Comment by Sarahtonein** [comment]
@Balugrizzly , 

CRUD branches have been created and commits pushed. Would like to discuss next time we're both online

**Comment by Sarahtonein** [comment]
CRUD operations have been added. Closing this issue,
