### ISSUE TITLE
Make Query Param Optional 

### ISSUE THREAD

**Issue by Balugrizzly** [BloomGameStudio/PlayerService#75]
Make Query Params  optional 

I have seen this in the GetPlayer endpoint

**Comment by Sarahtonein** [comment]
Is this for all CRUD operations?

**Comment by Balugrizzly** [comment]
This functionality and behavior should exists in general for everything including all "CRUD operations"
I have seen this not be the case in the GetPlayer endpoint
where when you dont provide the active param it will default to false
